name: Deploy Changed Notebooks to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Changed Notebooks to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Validate Databricks CLI Installation
        run: |
          databricks --version

      - name: Identify Changed Notebooks
        id: changes
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
              # For subsequent commits
              echo "Only changed"
              git diff --name-only --diff-filter=AM HEAD~1 HEAD notebooks/ > changed_files.txt
          else
              # For the first commit
              echo "First commit, deploying all notebooks"
              git ls-files notebooks/ > changed_files.txt
          fi
          cat changed_files.txt

      - name: Deploy Only Changed Notebooks
        if: success()
        env:
          DATABRICKS_HOST: "https://adb-2704412929221880.0.azuredatabricks.net/"
          DATABRICKS_TOKEN: "dapi2c154c340f172aed52d814616c94be1b"
        run: |
          while IFS= read -r notebook; do
            echo "Only changed $notebook"
            databricks workspace import --overwrite --language PYTHON "$notebook" "/$notebook"
          done < changed_files.txt
