name: Deploy Notebooks to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Notebooks to Prod Workspace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI for Prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
        run: |
          mkdir -p ~/.databricks
          echo -e "[DEFAULT]\nhost = $DATABRICKS_HOST\ntoken = $DATABRICKS_TOKEN" > ~/.databricks/config
          chmod 600 ~/.databricks/config

      - name: Deploy Notebooks to Prod Workspace
        run: |
          databricks workspace import_dir --overwrite notebooks /Production/notebooks

