name: Deploy Changed Notebooks to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Changed Notebooks to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Validate Databricks CLI Installation
        run: |
          databricks --version

      - name: Identify Changed Notebooks
        id: changes
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only HEAD~1 HEAD notebooks/ > changed_files.txt
          else
            echo "First commit, deploying all notebooks"
            find notebooks -type f > changed_files.txt
          fi
          cat changed_files.txt

      - name: Deploy Only Changed Notebooks
        if: steps.changes.outputs.changed_files != ''
        env:
          DATABRICKS_HOST: "https://adb-2704412929221880.0.azuredatabricks.net/"
          DATABRICKS_TOKEN: "dapi2c154c340f172aed52d814616c94be1b"
        run: |
          while IFS= read -r notebook; do
            databricks workspace import --overwrite "$notebook" "/notebooks/$notebook"
          done < changed_files.txt
